# this program creates a database with random sample data for the contact book
# columns are first_name, last_name, phone_number, email
# mock data generated by mockaroo

import sqlite3 # database
import os # removing files
import os.path # file paths

db_file_name = 'contact book.db'

def main():
    # see if database already exists
    if os.path.exists(db_file_name):
        # if it does, ask user if they want to replace it
        while True:
            choice = input('Database already exists. Erase current one and reinitialize it? (y/n)\n')
            if choice == 'y':
                break
            elif choice == 'n':
                print('Operation aborted.')
                return
        # remove current database
        os.remove(db_file_name)
    
    # connect to sqlite
    conn = sqlite3.connect(db_file_name)
    c = conn.cursor()
    
    # load mock data file
    
    # create table
    
    # for each entry in file, insert values into table

if __name__ == '__main__':
    main()